### ISSUE TITLE
Empty CDATA breaks highlighting

### ISSUE THREAD

**Issue by metalinspired** [tree-sitter-grammars/tree-sitter-xml#7]
Hi,

Just noticed that empty CDATA breaks formatting:
![Screenshot_20240214_112357](https://github.com/tree-sitter-grammars/tree-sitter-xml/assets/18539473/daf38ba0-92f7-4781-8c59-84b8d88a5c37)

**Comment by ObserverOfTime** [comment]
Fixed in e925b5de5cd1a31522e01c51d7668346950ce4ff

**Comment by metalinspired** [comment]
I updated to latest "release" but the issue is still present.
Am I doing something wrong ?

**Comment by ObserverOfTime** [comment]
I forgot to tag the new release.
